Repository AcademicHubOrg/AcademicHub, pull requests merged in 2023-11, with the labels that each got.

#5 Google o auth feature
  Identity/Identity.Core/UsersService.cs
  Identity/Identity.Data/UsersRepository.cs
  Identity/Identity.IntegrationTests/Identity.IntegrationTests.csproj
  Identity/Identity.IntegrationTests/IntegrationTest.cs
  Identity/Identity/Identity.csproj
  Identity/Identity/Program.cs
Labels: help wanted

#85 Repo cleanup
  .gitignore
  .idea/.idea.AcademicHub.dir/.idea/.gitignore
  .idea/.idea.AcademicHub.dir/.idea/indexLayout.xml
  .idea/.idea.AcademicHub.dir/.idea/vcs.xml
  .idea/vcs.xml
  .idea/workspace.xml
  AcademicHub.Common/.idea/.idea.AcademicHub.Common/.idea/.gitignore
  AcademicHub.Common/.idea/.idea.AcademicHub.Common/.idea/encodings.xml
  AcademicHub.Common/.idea/.idea.AcademicHub.Common/.idea/indexLayout.xml
  AcademicHub.Common/.idea/.idea.AcademicHub.Common/.idea/vcs.xml
  CourseStream/.idea/.idea.CourseStream/.idea/.gitignore
  CourseStream/.idea/.idea.CourseStream/.idea/dataSources.xml
  CourseStream/.idea/.idea.CourseStream/.idea/encodings.xml
  CourseStream/.idea/.idea.CourseStream/.idea/indexLayout.xml
  CourseStream/.idea/.idea.CourseStream/.idea/vcs.xml
  CourseStream/.idea/config/applicationhost.config
  CourseTemplate/.idea/.idea.CourseTemplate/.idea/.gitignore
  CourseTemplate/.idea/.idea.CourseTemplate/.idea/dataSources.xml
  CourseTemplate/.idea/.idea.CourseTemplate/.idea/encodings.xml
  CourseTemplate/.idea/.idea.CourseTemplate/.idea/indexLayout.xml
  CourseTemplate/.idea/.idea.CourseTemplate/.idea/misc.xml
  CourseTemplate/.idea/.idea.CourseTemplate/.idea/vcs.xml
  Identity/.idea/.idea.Identity/.idea/.gitignore
  Identity/.idea/.idea.Identity/.idea/indexLayout.xml
  Identity/.idea/.idea.Identity/.idea/vcs.xml
  Materials/.idea/.idea.Materials/.idea/.gitignore
  Materials/.idea/.idea.Materials/.idea/dataSources.xml
  Materials/.idea/.idea.Materials/.idea/encodings.xml
  Materials/.idea/.idea.Materials/.idea/indexLayout.xml
  Materials/.idea/.idea.Materials/.idea/vcs.xml
  README.md
  TryCommit
  frontend/.idea/.gitignore
  frontend/.idea/Frontend.iml
  frontend/.idea/inspectionProfiles/Project_Default.xml
  frontend/.idea/modules.xml
  frontend/.idea/vcs.xml
Labels: debt

#90 Fix issues related to the Authorization & exceptions handling
  AcademicHub.Common/CustomExceptions/CustomErrorHandlingMiddleware.cs
  AcademicHub.Common/CustomExceptions/CustomExceptionFilter.cs
  Identity/Identity.Core/Identity.Core.csproj
  Identity/Identity.sln
  Identity/Identity/EndpointHandlers.cs
  Identity/Identity/Identity.csproj
  Identity/Identity/Program.cs
Labels: bug, debt
